let produtos = [
    {
        "id": 1,
        "img": "/images/image-product-1.jpg",
        "Nome": "Fall Limited Edition <br>Sneakers",
        "Preco": "125.00",
        "Frete": "Frete grátis",
        "tumb1": "/images/image-product-1.jpg",
        "tumb2": "/images/image-product-2.jpg",
        "tumb3": "/images/image-product-3.jpg",
        "tumb4": "/images/image-product-4.jpg",
        "descricao": "These low-profile sneakers are your perfect casual wear <br>companion. Featuring a durable rubber outer sole, they'll <br>withstand everything the weather can offer.",
        "tamanho": [
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42"
        ],
        "malefemale": 1,
        "marca": "",
        "Tipo": "Casual",
        "Cor": "Amarelo"
    },
    {
        "id": 2,
        "img": "/images/Tenis 2.avif",
        "Nome": "Tênis de corrida de estabilidade e amortecimento",
        "Preco": 269.69,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 2.avif",
        "tumb2": "/images/Tenis 2 - tumb 1.avif",
        "tumb3": "/images/Tenis 2 - tumb 2.avif",
        "tumb4": "/images/Tenis 2 - tumb 3.avif",
        "descricao": "Tênis de corrida de estabilidade e amortecimento. Novo tênis de corrida sem marca ou treinador em fundo laranja. Calçado desportivo para homem. Par de calçados esportivos.",
        "tamanho": [
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42"
        ],
        "malefemale": 2,
        "marca": "Misuno",
        "Tipo": "Corrida",
        "Cor": "Azul"
    },
    {
        "id": 3,
        "img": "/images/Tenis 3.avif",
        "Nome": "Tênis Nike Court Vision Low Next Nature Masculino",
        "Preco": 599.84,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 3.avif",
        "tumb2": "https://imgnike-a.akamaihd.net/768x768/0137025EA2.jpg",
        "tumb3": "https://imgnike-a.akamaihd.net/768x768/0137025EA4.jpg",
        "tumb4": "https://imgnike-a.akamaihd.net/768x768/0137025EA3.jpg",
        "descricao": "Apaixonado pelo visual clássico do basquete dos anos 80, mas tem uma queda pela cultura acelerada dos jogos de hoje? Conheça o Nike Court Vision Low. Um clássico remixado com pelo menos 20% de materiais reciclados por peso, seu cabedal nítido e camadas costuradas mantêm a alma do estilo original. O colarinho baixo macio mantém a simplicidade e o conforto para o seu mundo.",
        "tamanho": [
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42"
        ],
        "malefemale": 0,
        "marca": "Nike",
        "Tipo": "Casual",
        "Cor": "Verde"
    },
    {
        "id": 4,
        "img": "/images/Tenis 4.avif",
        "Nome": "Tênis Feminino Nike Downshifter 13 Preto",
        "Preco": 449.99,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 4.avif",
        "tumb2": "https://imgnike-a.akamaihd.net/768x768/027983IDA4.jpg",
        "tumb3": "https://imgnike-a.akamaihd.net/768x768/027983IDA6.jpg",
        "tumb4": "https://imgnike-a.akamaihd.net/768x768/027983IDA5.jpg",
        "descricao": "Quer esteja começando sua jornada de corrida ou seja um especialista ansioso para mudar seu ritmo, o Downshifter 13 está pronto para o passeio. Com um cabedal renovado, amortecimento e durabilidade, ele ajuda você a encontrar aquele equipamento extra ou a dar o primeiro passo para ir em busca de seus objetivos.<br><br>Feito com Nike Grind<br><br>O solado é feito com pelo menos 15% de material Nike Grind, um material produzido com retalhos do processo de fabricação dos calçados.",
        "tamanho": [
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42"
        ],
        "malefemale": 1,
        "marca": "Nike",
        "Tipo": "Corrido",
        "Cor": "Preto"
    },
    {
        "id": 5,
        "img": "/images/Tenis 5.avif",
        "Nome": "Tênis Masculino Respirável Azurion Run, Tênis Masculino Branco e Verde / 39",
        "Preco": 249.95,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 5.avif",
        "tumb2": "https://estilobrasileiro.com.br/cdn/shop/products/AnyConv.com__3c9d1817-6a03-4a00-9165-bd67d614e566_700x.webp?v=1703884676",
        "tumb3": "https://cdn.shopify.com/s/files/1/0778/2298/4476/files/tenismasculino1_480x480_c502fe81-401f-4ebe-805d-51241511b0c4_480x480.webp?v=1697156109",
        "tumb4": "https://estilobrasileiro.com.br/cdn/shop/products/Sapatos-casuais-masculinos-de-inverno-sapatos-masculinos-adulto-outono-respir-vel-moda-cal-ados-esportivos-t.jpg__1_700x.webp?v=1703884676",
        "descricao": "Apresentamos o Tênis Casual Esportivo, ideal para quem busca um calçado confortável e resistente para o dia a dia. Disponível nas cores preto laranja, azul acinzentado, é perfeito para combinar com diversos looks. Enfrente qualquer terreno com confiança, graças ao solado antiderrapante do Sport Fashion. Sua segurança é nossa prioridade, para que você possa se concentrar no que realmente importa.",
        "tamanho": [
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42", 
            "43"
        ],
        "malefemale": 0,
        "marca": "Misuno",
        "Tipo": "Casual",
        "Cor": "Verde"
    },
    {
        "id": 6,
        "img": "/images/Tenis 6.avif",
        "Nome": "Tênis Nike Air Max SC Masculino",
        "Preco": 351.49,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 6.avif",
        "tumb2": "/images/Tenis 6 - tumb 2.avif",
        "tumb3": "/images/Tenis 6 - tumb 3.avif",
        "tumb4": "/images/Tenis 6 - tumb 4.avif",
        "descricao": "Com suas linhas fáceis, o visual das pistas de herança e, claro, amortecimento Air visível, o Nike Air Max SC é a finalização perfeita para qualquer look. A rica mistura de materiais confere profundida, enquanto o transforma em um tênis durável e leve para uso no dia a dia. <br>A revolucionária tecnologia Air foi introduzida nos calçados Nike em 1978. Em 1987, o Nike Air Max 1 foi lançado com tecnologia Air visível no calcanhar, permitindo aos fãs mais do que apenas a sensação de conforto do amortecimento Air — de repente, era possível enxergá-lo. Desde então, a próxima geração dos tênis Air Max se tornou um sucesso entre atletas e colecionadores, oferecendo combinações de cores marcantes e um amortecimento leve e confiável.",
        "tamanho": [
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48"
        ],
        "malefemale": 0,
        "marca": "Nike",
        "Tipo": "Casual",
        "Cor": "Preto"
    },
    {
        "id": 7,
        "img": "/images/Tenis 7.avif",
        "Nome": "Tênis Olympikus Venus 2 Feminino Rosa",
        "Preco": 152.15,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 7.avif",
        "tumb2": "https://a-static.mlcdn.com.br/800x560/tenis-olympikus-venus-2-feminino-rosa/n2esportes/141336/060a27641547a6d63b062b2aaef7dd9c.jpeg",
        "tumb3": "https://a-static.mlcdn.com.br/800x560/tenis-olympikus-venus-2-feminino-rosa/n2esportes/141336/777e44145d2777b1f74918793c72a14f.jpeg",
        "tumb4": "https://a-static.mlcdn.com.br/800x560/tenis-olympikus-venus-2-feminino-rosa/n2esportes/141336/8c5bfe347d95050d691f5fb1749e4e53.jpeg",
        "descricao": "O Olympikus Vênus 2 foi pensado exclusivamente para o público feminino, é o tênis ideal para quem busca conforto e praticidade. Seu solado possui a tecnologia de amortecimento Evasense, que proporciona leveza, maciez e maior flexibilidade para as atividades diárias. O cabedal é confeccionado com tecido Jacquard multicolor, que proporciona flexibilidade, leveza e alta resistência em todos os momentos do dia. Na parte superior conta com a vista em high frequency, que traz detalhes de brilho e relevo em sua composição. O forro apresenta tecido poliéster com espuma e o seu atacador é composto por tecido poliéster texturizado.",
        "tamanho": [
            "34",
            "35",
            "36",
            "37",
            "38",
            "39"
        ],
        "malefemale": 1,
        "marca": "Olympikus",
        "Tipo": "Corrida",
        "Cor": "Rosa"
    },
    {
        "id": 8,
        "img": "/images/Tenis 8.avif",
        "Nome": "Tênis Nike Interact Run Masculino",
        "Preco": 333.92,
        "Frete": "Frete grátis",
        "tumb1": "/images/Tenis 8.avif",
        "tumb2": "/images/Tenis 8 - tumb 2.avif",
        "tumb3": "/images/Tenis 8 - tumb 3.avif",
        "tumb4": "/images/Tenis 8 - tumb 4.avif",
        "descricao": "Passada suave <br><br>Espuma macia e responsiva na entressola proporciona uma passada confortável para a sua corrida e onde mais o seu dia te levar. A espuma elevada proporciona mais maciez.<br><br>Voe<br><br>O cabedal Flyknit tem zonas de respirabilidade onde seu pé mais aquece, especificamente na dianteira. Ela é forte e durável, ajudando a manter seu pé seguro a cada quilômetro. O cabedal arejado e respirável abraça o seu pé de forma livre e fácil.",
        "tamanho": [
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48"
        ],
        "malefemale": 0,
        "marca": "Nike",
        "Tipo": "Corrida",
        "Cor": "Verde"
    }
    
    
]
